# DSS Production Configuration with Azure Key Vault REST API Integration
spring:
  profiles:
    active: production

logging:
  level:
    eu.europa.esig.dss: INFO
    com.azure: WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Azure Key Vault REST API Configuration
dss:
  server-signing:
    # Azure Key Vault REST API integration
    azure-key-vault:
      vault-url: "${AZURE_KEY_VAULT_URI}"
      client-id: "${AZURE_CLIENT_ID}" 
      client-secret: "${AZURE_CLIENT_SECRET}"
      tenant-id: "${AZURE_TENANT_ID}"
      certificate-name: "boyar-signing-cert"
      # Connection settings
      connection-timeout: 30000
      read-timeout: 60000
      retry-attempts: 3
  
  # Certificate validation configuration
  certificate-verifier:
    commons-data-loader:
      proxy:
        http-enabled: false
        https-enabled: false
      connection-timeout: 10000
      socket-timeout: 30000
    aia-source:
      cache-data-loader:
        ttl-seconds: 3600
        max-cache-size: 1000
    crl-source:
      cache-data-loader:
        ttl-seconds: 3600
        max-cache-size: 1000
    ocsp-source:
      cache-data-loader:
        ttl-seconds: 3600
        max-cache-size: 1000

# Security configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: when-authorized
    info:
      enabled: true
    metrics:
      enabled: true

# Production security headers
server:
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
        same-site: strict
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
      remote-ip-header: x-forwarded-for

# API Key authentication for REST endpoints
sign:
  security:
    api-key:
      enabled: true
      header-name: "X-API-Key"
      key: "${SIGN_API_KEY}"